export interface SaasToolData {
  slug: string
  name: string
  category: string
  description: string
  website: string
  pricingModel: string
  startingPrice: string
  averageCostPerUser: number
  typicalCompanySpend: string
  commonWastePatterns: string[]
  optimizationTips: string[]
  alternatives: string[]
  idealFor: string
  marketPosition: string
  commonPriceRange: string
  signatureWastePattern: string
}

export const saasToolCategories = [
  "Project Management",
  "Communication",
  "CRM",
  "Development",
  "Design",
  "Marketing",
  "Cloud Infrastructure",
  "Security",
  "HR",
  "Finance",
  "Productivity",
  "Customer Support",
  "Analytics",
] as const

export type SaasToolCategory = (typeof saasToolCategories)[number]

export const saasTools: SaasToolData[] = [
  {
    slug: "slack",
    name: "Slack",
    category: "Communication",
    description:
      "Slack is a channel-based messaging platform that brings teams together with real-time communication, file sharing, and integrations with hundreds of business tools.",
    website: "https://slack.com",
    pricingModel: "Per user/month",
    startingPrice: "$7.25/user/month (Pro)",
    averageCostPerUser: 12.5,
    typicalCompanySpend: "$500-$8,000/month",
    commonWastePatterns: [
      "Paying for inactive or departed employees who still have active licenses",
      "Users on Business+ or Enterprise plans who only need Pro-level features",
      "Redundant channels and workspaces that fragment communication and increase costs",
      "Paying for Slack when Microsoft Teams is already included in Microsoft 365 subscriptions",
    ],
    optimizationTips: [
      "Audit user activity monthly and deactivate accounts with no logins in the past 30 days",
      "Downgrade users who do not use advanced compliance, SSO, or data retention features to the Pro plan",
      "Consolidate multiple workspaces into a single workspace with organized channels",
      "Negotiate annual billing for a 15-20% discount over monthly pricing",
    ],
    alternatives: ["Microsoft Teams", "Google Chat", "Discord"],
    idealFor: "Teams of 10-500 that need real-time messaging and integrations",
    marketPosition: "Dominant team-messaging platform; primary alternative is Microsoft Teams in Microsoft 365 shops.",
    commonPriceRange: "$8.75-15 per active user per month for Pro and Business+ tiers.",
    signatureWastePattern: "Inactive accounts billed for 30+ days because no one ran the deactivation cycle after layoffs or contractor rolloff.",
  },
  {
    slug: "salesforce",
    name: "Salesforce",
    category: "CRM",
    description:
      "Salesforce is the world's leading CRM platform, offering sales, service, marketing, and analytics tools to manage customer relationships and drive revenue growth.",
    website: "https://salesforce.com",
    pricingModel: "Per user/month (tiered editions)",
    startingPrice: "$25/user/month (Starter Suite)",
    averageCostPerUser: 150,
    typicalCompanySpend: "$2,000-$50,000/month",
    commonWastePatterns: [
      "Licenses assigned to users who rarely log in or only view dashboards occasionally",
      "Teams on Enterprise or Unlimited editions when Professional would suffice",
      "Paying for add-on products like CPQ or Pardot that are underutilized",
      "Duplicate or unused custom objects and storage overage charges",
    ],
    optimizationTips: [
      "Review login history reports quarterly and reassign or deactivate unused licenses",
      "Match each user to the lowest edition that supports their actual feature usage",
      "Audit installed AppExchange packages and remove those with minimal adoption",
      "Negotiate multi-year contracts during Salesforce's fiscal year-end (January) for best discounts",
    ],
    alternatives: ["HubSpot CRM", "Pipedrive", "Zoho CRM"],
    idealFor: "Sales teams of 20-10,000+ requiring enterprise-grade CRM",
    marketPosition: "Global market-leading CRM with the largest enterprise install base; the default choice for Fortune 500 sales orgs.",
    commonPriceRange: "$25-330 per user per month across Starter, Professional, Enterprise, and Unlimited editions.",
    signatureWastePattern: "Enterprise or Unlimited edition seats assigned to occasional dashboard viewers who would be fully served by Professional.",
  },
  {
    slug: "hubspot",
    name: "HubSpot",
    category: "CRM",
    description:
      "HubSpot offers an integrated suite of marketing, sales, service, and CMS tools built on a free CRM, designed to help growing businesses attract, engage, and delight customers.",
    website: "https://hubspot.com",
    pricingModel: "Tiered (Free, Starter, Professional, Enterprise)",
    startingPrice: "Free CRM; Starter from $20/month",
    averageCostPerUser: 45,
    typicalCompanySpend: "$800-$12,000/month",
    commonWastePatterns: [
      "Paying for Marketing Hub Professional when contact volume is well below tier limits",
      "Overlapping functionality with other tools like Mailchimp for email or Zendesk for support",
      "Unused Hub seats — companies often buy Sales Hub seats for reps who use it minimally",
      "Contacts exceeding the free tier limit when many are unengaged or duplicates",
    ],
    optimizationTips: [
      "Regularly purge unengaged contacts to stay within your contact tier and avoid overage fees",
      "Consolidate email marketing, CRM, and support into HubSpot to eliminate overlapping tool costs",
      "Use free CRM features before upgrading — many teams pay for features available at no cost",
      "Negotiate bundle discounts when purchasing multiple Hubs together",
    ],
    alternatives: ["Salesforce", "Pipedrive", "ActiveCampaign"],
    idealFor: "Growing companies of 5-500 employees wanting an all-in-one platform",
    marketPosition: "Mid-market all-in-one CRM and marketing platform; primary challenger to Salesforce in the SMB and growth segments.",
    commonPriceRange: "$20-1,200+ per month per Hub, scaling by contact tier and seat count.",
    signatureWastePattern: "Marketing Hub Professional retained at a contact tier well above current list size after a list-cleanup is overdue.",
  },
  {
    slug: "zoom",
    name: "Zoom",
    category: "Communication",
    description:
      "Zoom is a video communications platform offering meetings, webinars, chat, phone, and virtual events for businesses of all sizes.",
    website: "https://zoom.us",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "$13.33/user/month (Pro)",
    averageCostPerUser: 18,
    typicalCompanySpend: "$200-$5,000/month",
    commonWastePatterns: [
      "Pro or Business licenses for employees who only join meetings and never host",
      "Paying for Zoom Phone and Zoom Rooms features that go unused",
      "Maintaining Zoom alongside Microsoft Teams or Google Meet, creating redundant video tools",
      "Webinar add-on licenses purchased for one-time events but billed monthly",
    ],
    optimizationTips: [
      "Assign host licenses only to employees who actually schedule and host meetings regularly",
      "Use the free Basic plan for participants who only join meetings hosted by others",
      "Cancel Zoom if your team already has Microsoft Teams or Google Meet included in existing subscriptions",
      "Switch webinar add-ons to pay-per-use or event-based plans instead of monthly subscriptions",
    ],
    alternatives: ["Microsoft Teams", "Google Meet", "Webex"],
    idealFor: "Organizations of any size needing reliable video conferencing",
    marketPosition: "Default standalone video-conferencing platform; faces sustained pressure from Microsoft Teams and Google Meet bundled in productivity suites.",
    commonPriceRange: "$13.33-22.49 per user per month for Pro and Business tiers.",
    signatureWastePattern: "Pro host licenses paid for employees who only ever join meetings hosted by others and never schedule their own.",
  },
  {
    slug: "jira",
    name: "Jira",
    category: "Project Management",
    description:
      "Jira by Atlassian is the leading project tracking and issue management tool for agile software development teams, supporting Scrum, Kanban, and custom workflows.",
    website: "https://www.atlassian.com/software/jira",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "Free for up to 10 users; $7.75/user/month (Standard)",
    averageCostPerUser: 14,
    typicalCompanySpend: "$300-$8,000/month",
    commonWastePatterns: [
      "Licenses for non-technical stakeholders who only need read access to boards",
      "Premium tier licenses when Standard features cover actual usage patterns",
      "Paying for Jira alongside other project management tools like Asana or Monday.com",
      "Unused Jira Service Management or Jira Product Discovery add-ons still being billed",
    ],
    optimizationTips: [
      "Use free stakeholder or read-only access for non-contributor users instead of full licenses",
      "Audit which Premium features (advanced roadmaps, sandbox) are actually used before renewal",
      "Consolidate project management into one tool rather than running Jira and another PM tool in parallel",
      "Move to Cloud from Server/Data Center if self-hosting costs exceed cloud subscription costs",
    ],
    alternatives: ["Linear", "Asana", "ClickUp"],
    idealFor: "Software development teams of 10-5,000",
    marketPosition: "Dominant agile issue tracker for engineering organizations; the de facto standard at companies running Scrum or Kanban at scale.",
    commonPriceRange: "$7.75-15.25 per user per month for Standard and Premium Cloud tiers.",
    signatureWastePattern: "Full Jira seats handed to non-technical stakeholders who only need read-only access to view a sprint board once a week.",
  },
  {
    slug: "asana",
    name: "Asana",
    category: "Project Management",
    description:
      "Asana is a work management platform that helps teams orchestrate work from daily tasks to strategic initiatives with projects, timelines, and automation.",
    website: "https://asana.com",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "Free for up to 10 users; $10.99/user/month (Starter)",
    averageCostPerUser: 24.99,
    typicalCompanySpend: "$300-$6,000/month",
    commonWastePatterns: [
      "Advanced tier licenses for teams that primarily use basic task lists and boards",
      "Paying for users who check Asana infrequently and could use guest or viewer access",
      "Running Asana alongside Jira, Monday.com, or Trello for different departments",
      "Enterprise features like custom branding and SAML SSO purchased but never configured",
    ],
    optimizationTips: [
      "Audit seat usage quarterly and convert infrequent users to free guest accounts",
      "Evaluate whether the Starter plan covers your needs before paying for Advanced",
      "Standardize on one project management tool across the organization to eliminate overlap",
      "Leverage Asana's free tier for small teams or departments with simple needs",
    ],
    alternatives: ["Monday.com", "ClickUp", "Trello"],
    idealFor: "Cross-functional teams of 10-1,000 managing diverse project types",
    marketPosition: "Mid-market work-management leader; competes head-to-head with monday.com and ClickUp for non-engineering project workflows.",
    commonPriceRange: "$10.99-24.99 per user per month for Starter and Advanced tiers.",
    signatureWastePattern: "Advanced-tier seats assigned to project members who never use the workload, portfolio, or goals features that justify the upgrade.",
  },
  {
    slug: "notion",
    name: "Notion",
    category: "Productivity",
    description:
      "Notion is an all-in-one workspace combining notes, docs, databases, wikis, and project management into a single flexible tool for teams and individuals.",
    website: "https://notion.so",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "Free for individuals; $10/user/month (Plus)",
    averageCostPerUser: 10,
    typicalCompanySpend: "$200-$4,000/month",
    commonWastePatterns: [
      "Business plan licenses for teams that only use basic docs and simple databases",
      "Overlapping with Confluence, Google Docs, or SharePoint for documentation",
      "Paying for members who rarely edit and could use free guest access",
      "AI add-on ($8/user/month) purchased company-wide but used by a fraction of the team",
    ],
    optimizationTips: [
      "Use guest access for external collaborators and infrequent internal users",
      "Consolidate documentation tools — replace Confluence or Google Docs if Notion covers the same needs",
      "Start with the Plus plan and only upgrade to Business when SSO or advanced permissions are truly needed",
      "Limit the Notion AI add-on to users who actively use it rather than enabling it company-wide",
    ],
    alternatives: ["Confluence", "Coda", "Slite"],
    idealFor: "Teams of 5-500 wanting a flexible all-in-one workspace",
    marketPosition: "Leading flexible workspace tool, especially among startups; squeezes Confluence on docs and Asana on lightweight project tracking.",
    commonPriceRange: "$10-15 per user per month for Plus and Business tiers, plus $8-10 per user for the AI add-on.",
    signatureWastePattern: "Notion AI add-on enabled company-wide while only a fraction of the team actually uses it on a recurring basis.",
  },
  {
    slug: "microsoft-365",
    name: "Microsoft 365",
    category: "Productivity",
    description:
      "Microsoft 365 is a comprehensive productivity suite including Outlook, Teams, Word, Excel, PowerPoint, SharePoint, OneDrive, and enterprise security features.",
    website: "https://microsoft.com/microsoft-365",
    pricingModel: "Per user/month (tiered editions)",
    startingPrice: "$6/user/month (Business Basic)",
    averageCostPerUser: 22,
    typicalCompanySpend: "$500-$25,000/month",
    commonWastePatterns: [
      "E5 licenses for users who need only email and basic Office apps (E1 or E3 would suffice)",
      "Licenses for former employees, contractors, or shared accounts that are no longer active",
      "Paying for desktop Office apps when web-only versions in Business Basic would work",
      "Unused add-ons like Power BI Pro, Visio, or Project licenses collecting dust",
    ],
    optimizationTips: [
      "Right-size license tiers: assign E1/Business Basic to frontline workers and E3/E5 only where advanced features are needed",
      "Automate license reclamation when employees leave using Azure AD lifecycle policies",
      "Audit add-on license usage quarterly and remove subscriptions with low adoption rates",
      "Negotiate Enterprise Agreements for organizations with 500+ seats for volume discounts",
    ],
    alternatives: ["Google Workspace", "Zoho Workplace", "LibreOffice (self-hosted)"],
    idealFor: "Organizations of all sizes, especially enterprises with 50+ employees",
    marketPosition: "Dominant enterprise productivity suite; the default choice for organizations standardized on Windows and Active Directory.",
    commonPriceRange: "$6-57 per user per month across Business Basic, Business Standard, E3, and E5 tiers.",
    signatureWastePattern: "E5 licenses provisioned organization-wide for security features that only the IT and compliance teams actually consume.",
  },
  {
    slug: "google-workspace",
    name: "Google Workspace",
    category: "Productivity",
    description:
      "Google Workspace provides cloud-native productivity and collaboration tools including Gmail, Google Drive, Docs, Sheets, Meet, and Chat for business teams.",
    website: "https://workspace.google.com",
    pricingModel: "Per user/month (tiered editions)",
    startingPrice: "$7/user/month (Business Starter)",
    averageCostPerUser: 14,
    typicalCompanySpend: "$300-$15,000/month",
    commonWastePatterns: [
      "Business Plus or Enterprise licenses for users who only use Gmail and Drive",
      "Paying for storage tiers when files could be archived or cleaned up to stay within limits",
      "Duplicate subscriptions — some users have both Google Workspace and Microsoft 365 licenses",
      "Google Vault and security features billed but never configured or used",
    ],
    optimizationTips: [
      "Assign Business Starter to light users (email and basic storage) and Business Standard only where needed",
      "Implement storage policies to prevent unnecessary large file accumulation",
      "Eliminate overlap with Microsoft 365 — choose one productivity suite as the standard",
      "Use Google Workspace's built-in tools (Sites, Forms, Chat) before purchasing third-party alternatives",
    ],
    alternatives: ["Microsoft 365", "Zoho Workplace", "Fastmail + Nextcloud"],
    idealFor: "Teams of 5-5,000 that prefer cloud-native collaboration",
    marketPosition: "The cloud-native productivity standard for tech-forward and startup-heavy organizations; primary alternative is Microsoft 365.",
    commonPriceRange: "$7-23 per user per month across Business Starter, Standard, and Plus tiers.",
    signatureWastePattern: "Business Plus or Enterprise seats assigned to users who only ever touch Gmail and a few shared Drive folders.",
  },
  {
    slug: "dropbox",
    name: "Dropbox",
    category: "Productivity",
    description:
      "Dropbox is a cloud storage and file synchronization service that lets teams store, share, and collaborate on files with desktop and mobile sync.",
    website: "https://dropbox.com",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "$15/user/month (Business)",
    averageCostPerUser: 22,
    typicalCompanySpend: "$300-$5,000/month",
    commonWastePatterns: [
      "Paying for Dropbox when Google Drive or OneDrive is already included in existing productivity suites",
      "Advanced or Enterprise tier licenses for teams that only need basic file storage and sharing",
      "Licenses for users who store minimal files and rarely access the platform",
      "DocSend and Sign add-ons billed but rarely used by most team members",
    ],
    optimizationTips: [
      "Evaluate whether Google Drive or OneDrive already meets your file storage needs before renewing",
      "Downgrade to Business tier if your team doesn't use Advanced features like watermarking or classification",
      "Remove licenses for users with low storage consumption — they may not need dedicated cloud storage",
      "Consolidate file storage into one platform to reduce per-user costs and simplify management",
    ],
    alternatives: ["Google Drive", "OneDrive", "Box"],
    idealFor: "Teams of 5-200 needing reliable file sync and sharing",
    marketPosition: "Standalone cloud-storage incumbent; increasingly displaced by storage included in Google Workspace or Microsoft 365 bundles.",
    commonPriceRange: "$15-26 per user per month for Business and Advanced tiers, with a 3-seat minimum.",
    signatureWastePattern: "Standalone Dropbox kept on alongside the Drive or OneDrive storage already paid for inside the company productivity suite.",
  },
  {
    slug: "monday-com",
    name: "Monday.com",
    category: "Project Management",
    description:
      "Monday.com is a work operating system that enables teams to build custom workflows, manage projects, and automate processes with a visual, no-code interface.",
    website: "https://monday.com",
    pricingModel: "Per user/month (tiered, minimum 3 seats)",
    startingPrice: "$9/seat/month (Basic)",
    averageCostPerUser: 16,
    typicalCompanySpend: "$300-$8,000/month",
    commonWastePatterns: [
      "Pro or Enterprise seats for team members who only view boards and never configure workflows",
      "Minimum seat purchases exceeding actual team size on each tier",
      "Running Monday.com alongside Asana, Jira, or ClickUp for different departments",
      "Paying for Monday CRM or Monday Dev add-ons with low adoption",
    ],
    optimizationTips: [
      "Use viewer-only seats (included free) for stakeholders who just need to see project status",
      "Consolidate all project management into Monday.com or choose an alternative — avoid paying for two PM tools",
      "Match your plan tier to the features actually used by your team — most teams are fine on Standard",
      "Negotiate annual billing and multi-year discounts for teams larger than 25 seats",
    ],
    alternatives: ["Asana", "ClickUp", "Smartsheet"],
    idealFor: "Teams of 10-500 wanting visual, customizable project management",
    marketPosition: "Visual work-OS leader for non-technical teams; primary alternatives are Asana and ClickUp on the upmarket side and Trello on the lightweight side.",
    commonPriceRange: "$9-19 per seat per month for Basic, Standard, and Pro tiers, sold in 3-seat minimums.",
    signatureWastePattern: "3-seat minimum bracket purchased on a higher tier than the team currently uses, locking in unused capacity each renewal.",
  },
  {
    slug: "trello",
    name: "Trello",
    category: "Project Management",
    description:
      "Trello is a visual collaboration tool using boards, lists, and cards to organize tasks and projects with a simple, Kanban-style interface.",
    website: "https://trello.com",
    pricingModel: "Per user/month (freemium)",
    startingPrice: "Free; $5/user/month (Standard)",
    averageCostPerUser: 10,
    typicalCompanySpend: "$100-$2,000/month",
    commonWastePatterns: [
      "Premium licenses for users who only use basic boards with no automations or views",
      "Paying for Trello when a more comprehensive PM tool like Jira or Asana would consolidate needs",
      "Power-Up subscriptions for third-party integrations that are rarely used",
      "Enterprise tier purchased for compliance features that a smaller team doesn't require",
    ],
    optimizationTips: [
      "Keep lightweight users on the free tier — it supports up to 10 boards per workspace",
      "Upgrade only the users who need calendar view, timeline, and advanced automations",
      "Consider migrating to a more full-featured tool if your team has outgrown Trello's simplicity",
      "Use built-in Butler automations instead of paying for third-party Power-Ups",
    ],
    alternatives: ["Asana", "Notion", "ClickUp"],
    idealFor: "Small teams of 3-50 wanting simple, visual task management",
    marketPosition: "The original Kanban board tool, now part of Atlassian; sits at the lightweight end of the project-management category.",
    commonPriceRange: "$5-17.50 per user per month for Standard and Premium tiers.",
    signatureWastePattern: "Premium licenses kept on for users who never touch calendar view, timeline, or Butler automation features that justify the upgrade.",
  },
  {
    slug: "zendesk",
    name: "Zendesk",
    category: "Customer Support",
    description:
      "Zendesk is a customer service and engagement platform offering ticketing, live chat, messaging, and help center tools for support teams.",
    website: "https://zendesk.com",
    pricingModel: "Per agent/month (tiered)",
    startingPrice: "$19/agent/month (Support Team)",
    averageCostPerUser: 69,
    typicalCompanySpend: "$500-$15,000/month",
    commonWastePatterns: [
      "Suite Professional or Enterprise licenses for agents who only handle basic email tickets",
      "Light agent seats billed for employees who rarely access the support system",
      "Paying for Zendesk Sell (CRM) alongside Salesforce or HubSpot CRM",
      "Advanced AI and bot add-ons purchased but never fully implemented or trained",
    ],
    optimizationTips: [
      "Audit agent activity and convert infrequent users to light agents or remove their seats entirely",
      "Match agent license tiers to actual feature usage — most teams are well-served by Suite Team or Professional",
      "Consolidate CRM and support into one platform instead of paying for Zendesk Sell and another CRM",
      "Implement self-service knowledge bases and chatbots to reduce the number of agent seats needed",
    ],
    alternatives: ["Freshdesk", "Intercom", "Help Scout"],
    idealFor: "Support teams of 5-500 agents handling multi-channel customer inquiries",
    marketPosition: "Enterprise-grade customer-support platform; the leading omnichannel ticketing system for scale support operations.",
    commonPriceRange: "$19-115 per agent per month across Suite Team, Growth, Professional, and Enterprise tiers.",
    signatureWastePattern: "Suite Professional or Enterprise seats provisioned for agents who only handle plain email tickets and never use SLAs or routing.",
  },
  {
    slug: "intercom",
    name: "Intercom",
    category: "Customer Support",
    description:
      "Intercom is a customer messaging platform combining live chat, chatbots, help center, and proactive messaging to engage customers across their lifecycle.",
    website: "https://intercom.com",
    pricingModel: "Per seat/month + usage-based (resolutions)",
    startingPrice: "$39/seat/month (Essential)",
    averageCostPerUser: 79,
    typicalCompanySpend: "$500-$10,000/month",
    commonWastePatterns: [
      "Seats assigned to team members who rarely handle customer conversations",
      "Paying for Proactive Support or Product Tours features that are not actively used",
      "Usage-based overage charges from chatbot resolutions exceeding plan limits",
      "Running Intercom alongside Zendesk or Freshdesk, duplicating support tool costs",
    ],
    optimizationTips: [
      "Remove seats for team members with fewer than 5 conversations per month",
      "Optimize chatbot flows to resolve common questions and reduce overage resolution costs",
      "Consolidate customer support into either Intercom or your existing helpdesk — not both",
      "Evaluate whether the Essential plan covers your needs before upgrading to Advanced or Expert",
    ],
    alternatives: ["Zendesk", "Freshdesk", "Drift"],
    idealFor: "SaaS companies and startups with 5-200 support and success team members",
    marketPosition: "Leading conversational support platform for SaaS companies; pioneered the in-app messenger and now competes on AI bot resolutions.",
    commonPriceRange: "$39-139 per seat per month plus usage-based AI resolution fees.",
    signatureWastePattern: "Chatbot-resolution overage charges piling up because flow logic was never tuned after the original launch configuration.",
  },
  {
    slug: "datadog",
    name: "Datadog",
    category: "Analytics",
    description:
      "Datadog is a cloud monitoring and analytics platform providing infrastructure monitoring, APM, log management, and security for modern applications.",
    website: "https://datadoghq.com",
    pricingModel: "Usage-based (per host, per GB, per million events)",
    startingPrice: "$15/host/month (Infrastructure Pro)",
    averageCostPerUser: 35,
    typicalCompanySpend: "$1,000-$50,000/month",
    commonWastePatterns: [
      "Monitoring hosts that have been decommissioned or are idle development/staging environments",
      "Retaining logs for 15 or 30 days when 7-day retention would suffice for most operational needs",
      "Ingesting metrics from services that no one actively monitors or alerts on",
      "Paying for APM traces, Synthetics, and RUM for applications that could use cheaper alternatives",
    ],
    optimizationTips: [
      "Audit monitored hosts monthly and remove decommissioned or non-critical development instances",
      "Configure log exclusion filters and reduce retention periods to control log ingestion costs",
      "Use metric tags strategically and drop unused custom metrics to lower per-host costs",
      "Negotiate committed-use discounts if your monthly spend exceeds $5,000",
    ],
    alternatives: ["New Relic", "Grafana Cloud", "Prometheus + Grafana (self-hosted)"],
    idealFor: "Engineering teams running 10-10,000+ hosts in cloud infrastructure",
    marketPosition: "Premium cloud monitoring and observability platform; the default choice at growth-stage and enterprise engineering orgs.",
    commonPriceRange: "$15-34 per host per month for Infrastructure plus usage charges for logs, APM, and custom metrics.",
    signatureWastePattern: "Custom-metric and log-ingest overage charges driven by services no one actively monitors or alerts on.",
  },
  {
    slug: "snowflake",
    name: "Snowflake",
    category: "Analytics",
    description:
      "Snowflake is a cloud data platform offering data warehousing, data lakes, data engineering, and data sharing with a pay-per-use consumption model.",
    website: "https://snowflake.com",
    pricingModel: "Usage-based (compute credits + storage)",
    startingPrice: "Usage-based; ~$2-3/credit (Standard)",
    averageCostPerUser: 100,
    typicalCompanySpend: "$2,000-$100,000/month",
    commonWastePatterns: [
      "Warehouses left running during nights, weekends, and periods of no query activity",
      "Oversized warehouse tiers (XL, 2XL) for queries that would run fine on smaller sizes",
      "Storing historical data that is never queried but still occupying paid storage",
      "Redundant data copies and materialized views consuming compute credits on refresh",
    ],
    optimizationTips: [
      "Enable auto-suspend on all warehouses with a 1-5 minute timeout to stop paying for idle compute",
      "Right-size warehouses based on actual query performance — start small and scale up only when needed",
      "Implement data lifecycle policies to archive or delete data that is no longer queried",
      "Use resource monitors to set spending alerts and prevent unexpected cost spikes",
    ],
    alternatives: ["BigQuery", "Databricks", "Amazon Redshift"],
    idealFor: "Data teams at companies processing medium to massive data volumes",
    marketPosition: "Leading independent cloud data warehouse; competes with BigQuery, Redshift, and Databricks across analytics-native workloads.",
    commonPriceRange: "Usage-based; ~$2-4 per compute credit plus storage, varies by warehouse size and edition.",
    signatureWastePattern: "Warehouses left running through nights and weekends because auto-suspend was never set on a low timeout.",
  },
  {
    slug: "twilio",
    name: "Twilio",
    category: "Communication",
    description:
      "Twilio is a cloud communications platform providing APIs for SMS, voice, video, email (SendGrid), and authentication for developers building communication features.",
    website: "https://twilio.com",
    pricingModel: "Usage-based (per message, per minute, per API call)",
    startingPrice: "Pay-as-you-go; SMS from $0.0079/message",
    averageCostPerUser: 25,
    typicalCompanySpend: "$500-$20,000/month",
    commonWastePatterns: [
      "Phone numbers provisioned for testing or legacy features that are still being billed monthly",
      "Sending SMS to landlines or invalid numbers, wasting message credits",
      "Using Twilio for functions that could be handled by cheaper alternatives or built-in features",
      "Not leveraging volume discounts despite consistent high-volume messaging",
    ],
    optimizationTips: [
      "Audit active phone numbers monthly and release numbers that are no longer in use",
      "Validate phone numbers before sending to avoid charges for undeliverable messages",
      "Negotiate committed-use discounts when monthly spend exceeds $1,000",
      "Evaluate whether MessageBird or Amazon SNS could handle simpler messaging needs at lower cost",
    ],
    alternatives: ["MessageBird", "Vonage", "Amazon SNS"],
    idealFor: "Developers and companies embedding communications into their products",
    marketPosition: "Market-leading CPaaS for developer-built SMS, voice, and email; competes with MessageBird and the cloud providers' native messaging APIs.",
    commonPriceRange: "Usage-based; SMS from $0.0079 per message, voice from $0.013 per minute, plus monthly phone-number fees.",
    signatureWastePattern: "Phone numbers from old features or test environments still billed every month long after the use case was retired.",
  },
  {
    slug: "stripe",
    name: "Stripe",
    category: "Finance",
    description:
      "Stripe is a payment processing platform providing APIs for online payments, subscriptions, invoicing, and financial infrastructure for internet businesses.",
    website: "https://stripe.com",
    pricingModel: "Transaction-based (percentage + fixed fee)",
    startingPrice: "2.9% + $0.30 per transaction",
    averageCostPerUser: 50,
    typicalCompanySpend: "$500-$50,000/month",
    commonWastePatterns: [
      "Not negotiating custom rates despite processing over $100K/month in volume",
      "Paying for Stripe Billing, Radar, and other add-ons that overlap with other tools",
      "High chargeback and dispute rates increasing effective processing costs",
      "Using Stripe for invoice payments when ACH or bank transfers would have much lower fees",
    ],
    optimizationTips: [
      "Request custom pricing when monthly processing volume exceeds $100,000",
      "Route high-value B2B transactions through ACH ($0.80 per transaction) instead of card payments",
      "Implement Stripe Radar rules to reduce fraud and chargebacks that inflate costs",
      "Consolidate payment processing — use Stripe's built-in features before adding third-party tools",
    ],
    alternatives: ["Braintree", "Adyen", "Square"],
    idealFor: "Online businesses and SaaS companies processing recurring payments",
    marketPosition: "Default payment-processing API for internet businesses; primary alternatives are Adyen at the enterprise tier and Braintree for legacy stacks.",
    commonPriceRange: "Transaction-based; 2.9% + $0.30 per online card transaction, with negotiated rates above $100K monthly volume.",
    signatureWastePattern: "Standard 2.9% + 30c card rate paid on every transaction despite monthly volume well above the threshold for negotiated custom pricing.",
  },
  {
    slug: "shopify",
    name: "Shopify",
    category: "Finance",
    description:
      "Shopify is an e-commerce platform that enables businesses to create online stores, manage inventory, process payments, and sell across multiple channels.",
    website: "https://shopify.com",
    pricingModel: "Monthly subscription + transaction fees",
    startingPrice: "$39/month (Basic)",
    averageCostPerUser: 79,
    typicalCompanySpend: "$79-$2,000/month (plus transaction fees)",
    commonWastePatterns: [
      "Advanced or Plus plans when Basic plan features are sufficient for current sales volume",
      "Paying for multiple Shopify apps that duplicate functionality or are no longer used",
      "Using third-party payment processors and paying Shopify's additional transaction fees",
      "Plus plan ($2,300/month) subscriptions maintained despite not using enterprise features",
    ],
    optimizationTips: [
      "Audit installed Shopify apps quarterly — remove apps that are unused or redundant",
      "Use Shopify Payments to avoid the additional 0.5-2% transaction fee charged for external processors",
      "Evaluate whether you truly need the Advanced plan or if Basic covers your sales volume",
      "Consolidate apps by using Shopify's built-in features (email marketing, analytics) before paying for add-ons",
    ],
    alternatives: ["WooCommerce", "BigCommerce", "Squarespace Commerce"],
    idealFor: "E-commerce businesses of all sizes, from solo entrepreneurs to mid-market brands",
    marketPosition: "Dominant hosted e-commerce platform for SMB and mid-market brands; primary alternatives are WooCommerce on WordPress and BigCommerce upmarket.",
    commonPriceRange: "$39-2,300 per month across Basic, Shopify, Advanced, and Plus plans, plus per-transaction fees.",
    signatureWastePattern: "Third-party Shopify apps stacked into the monthly bill that duplicate functionality already covered by built-in store features.",
  },
  {
    slug: "figma",
    name: "Figma",
    category: "Design",
    description:
      "Figma is a collaborative interface design tool for creating UI/UX designs, prototypes, and design systems in real-time with team collaboration features.",
    website: "https://figma.com",
    pricingModel: "Per editor/month (viewers free)",
    startingPrice: "Free (Starter); $15/editor/month (Professional)",
    averageCostPerUser: 15,
    typicalCompanySpend: "$150-$3,000/month",
    commonWastePatterns: [
      "Full editor seats assigned to developers or PMs who only need to view and inspect designs",
      "Organization plan ($45/editor/month) purchased when Professional covers most teams' needs",
      "FigJam editor seats for users who rarely use the whiteboarding tool",
      "Paying for Dev Mode seats separately when they could be consolidated",
    ],
    optimizationTips: [
      "Keep non-designers (developers, PMs, stakeholders) as free viewers — they can still inspect and comment",
      "Audit editor usage monthly and convert infrequent editors to viewer accounts",
      "Use Professional plan before jumping to Organization unless you need centralized design system libraries",
      "Consolidate FigJam usage with free alternatives like Miro's free tier or Notion whiteboards",
    ],
    alternatives: ["Sketch", "Adobe XD", "Penpot"],
    idealFor: "Design teams of 3-100 editors collaborating on product design",
    marketPosition: "Dominant collaborative interface-design tool; effectively displaced Sketch and Adobe XD as the standard for product design teams.",
    commonPriceRange: "$15-45 per editor per month for Professional and Organization tiers; viewers free.",
    signatureWastePattern: "Full editor seats provisioned for developers, PMs, and stakeholders who only ever inspect or comment on files.",
  },
  {
    slug: "github",
    name: "GitHub",
    category: "Development",
    description:
      "GitHub is the world's largest code hosting platform providing Git repositories, CI/CD with Actions, code review, project management, and developer collaboration tools.",
    website: "https://github.com",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "Free for public repos; $4/user/month (Team)",
    averageCostPerUser: 21,
    typicalCompanySpend: "$200-$10,000/month",
    commonWastePatterns: [
      "Enterprise Cloud seats for developers who only need Team-level features",
      "Paying for outside collaborator seats when repository-level permissions would suffice",
      "GitHub Actions minutes exceeding the included allocation due to inefficient CI/CD pipelines",
      "GitHub Copilot Business licenses ($19/user/month) for developers who rarely use the AI assistant",
    ],
    optimizationTips: [
      "Use the Team plan for most developers and reserve Enterprise for teams needing SAML SSO and audit logs",
      "Optimize GitHub Actions workflows to reduce build times and stay within included minutes",
      "Audit Copilot usage data and remove licenses for developers with low acceptance rates",
      "Use outside collaborator access for contractors instead of full team member seats",
    ],
    alternatives: ["GitLab", "Bitbucket", "Azure DevOps"],
    idealFor: "Development teams of 5-5,000 using Git-based workflows",
    marketPosition: "World's largest code-hosting platform; default repository, code-review, and CI/CD home for most engineering teams outside Microsoft and GitLab shops.",
    commonPriceRange: "$4-21 per user per month for Team and Enterprise Cloud, plus $19-39 per user for Copilot Business or Enterprise.",
    signatureWastePattern: "Copilot Business seats kept on for developers whose acceptance rate sits in the single digits month after month.",
  },
  {
    slug: "gitlab",
    name: "GitLab",
    category: "Development",
    description:
      "GitLab is a complete DevOps platform providing source code management, CI/CD, security scanning, and project management in a single application.",
    website: "https://gitlab.com",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "Free; $29/user/month (Premium)",
    averageCostPerUser: 29,
    typicalCompanySpend: "$300-$15,000/month",
    commonWastePatterns: [
      "Ultimate licenses ($99/user/month) for teams that do not use security scanning or compliance features",
      "Seats for inactive developers or contractors who completed their engagement",
      "Self-managed instances with infrastructure costs exceeding SaaS subscription costs",
      "Paying for GitLab CI/CD compute minutes beyond what optimized pipelines require",
    ],
    optimizationTips: [
      "Evaluate whether Premium covers your needs before committing to Ultimate tier",
      "Automate seat deprovisioning when team members leave or become inactive",
      "Compare self-managed total cost of ownership against GitLab SaaS pricing",
      "Optimize CI/CD pipelines with caching and parallel jobs to reduce compute minute consumption",
    ],
    alternatives: ["GitHub", "Bitbucket", "Azure DevOps"],
    idealFor: "Engineering organizations of 20-2,000 wanting an integrated DevOps platform",
    marketPosition: "Primary GitHub competitor with a built-in DevOps stack; favored by orgs that want SCM, CI/CD, and security scanning under one vendor.",
    commonPriceRange: "$29-99 per user per month for Premium and Ultimate self-managed and SaaS tiers.",
    signatureWastePattern: "Ultimate-tier seats kept across the engineering org while the security and compliance scanners that justify the upgrade go unconfigured.",
  },
  {
    slug: "atlassian",
    name: "Atlassian (Suite)",
    category: "Development",
    description:
      "Atlassian offers a suite of collaboration tools including Jira, Confluence, Trello, and Bitbucket for project management, documentation, and code collaboration.",
    website: "https://atlassian.com",
    pricingModel: "Per user/month per product (tiered)",
    startingPrice: "Free tiers available; Standard from $7.75/user/month per product",
    averageCostPerUser: 30,
    typicalCompanySpend: "$500-$20,000/month",
    commonWastePatterns: [
      "Licensing multiple Atlassian products (Jira + Confluence + Bitbucket) when usage is concentrated in one",
      "Premium or Enterprise tiers across all products when Standard would suffice for most",
      "Confluence licenses for teams that have moved documentation to Notion or Google Docs",
      "Bitbucket seats maintained despite the engineering team using GitHub",
    ],
    optimizationTips: [
      "Audit usage across all Atlassian products and eliminate licenses for tools with low adoption",
      "Negotiate Atlassian Cloud bundle pricing when using multiple products together",
      "Standardize on Atlassian or an alternative stack — avoid paying for both Confluence and Notion",
      "Use Atlassian's free tier (up to 10 users) for small teams or departments with limited needs",
    ],
    alternatives: ["GitHub + Notion", "Linear + Notion", "Azure DevOps"],
    idealFor: "Software teams of 10-5,000 needing integrated project and code management",
    marketPosition: "Suite vendor behind Jira, Confluence, and Bitbucket; the standard collaboration stack for traditional enterprise engineering organizations.",
    commonPriceRange: "$7.75-15.25 per user per month per product, with bundle discounts for multi-product Cloud subscriptions.",
    signatureWastePattern: "Bitbucket seats still being billed across the engineering team long after the org migrated its repos to GitHub or GitLab.",
  },
  {
    slug: "adobe-creative-cloud",
    name: "Adobe Creative Cloud",
    category: "Design",
    description:
      "Adobe Creative Cloud provides industry-standard creative applications including Photoshop, Illustrator, InDesign, Premiere Pro, After Effects, and 20+ other tools.",
    website: "https://adobe.com/creativecloud",
    pricingModel: "Per user/month (single app or all apps)",
    startingPrice: "$22.99/month (single app); $59.99/month (All Apps)",
    averageCostPerUser: 59.99,
    typicalCompanySpend: "$500-$10,000/month",
    commonWastePatterns: [
      "All Apps licenses for users who only use 1-2 applications like Photoshop and Illustrator",
      "Creative Cloud licenses maintained for employees who have left or changed roles",
      "Paying for desktop apps when Adobe Express or web alternatives would cover casual design needs",
      "Stock photo credits and Adobe Fonts subscriptions included in plans but never used",
    ],
    optimizationTips: [
      "Assign single-app licenses ($22.99/month) to users who only need Photoshop or Illustrator",
      "Audit Creative Cloud usage via the Admin Console and reclaim licenses with zero or low usage",
      "Evaluate Canva or Figma for non-designers who need basic visual content creation",
      "Negotiate volume licensing discounts for teams of 10+ through Adobe's enterprise sales",
    ],
    alternatives: ["Canva", "Affinity Suite", "Figma"],
    idealFor: "Creative teams of 5-200 producing professional visual content",
    marketPosition: "The industry-standard professional creative suite; Photoshop, Illustrator, and Premiere remain the defaults across agencies and brand teams.",
    commonPriceRange: "$22.99 per app per month or $59.99 per user per month for All Apps; volume licensing reduces enterprise rates.",
    signatureWastePattern: "All Apps subscriptions retained for users who only open Photoshop or Illustrator and could move to a single-app plan at a third the price.",
  },
  {
    slug: "canva",
    name: "Canva",
    category: "Design",
    description:
      "Canva is a visual design platform offering templates, drag-and-drop editing, and collaboration tools for creating presentations, social media graphics, documents, and more.",
    website: "https://canva.com",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "Free; $13/user/month (Canva Pro/Teams)",
    averageCostPerUser: 13,
    typicalCompanySpend: "$100-$2,000/month",
    commonWastePatterns: [
      "Teams plan licenses for casual users who could work within the free tier's capabilities",
      "Overlapping with Adobe Creative Cloud for teams that need both professional and quick design tools",
      "Paying for premium stock photos and templates that the team rarely uses",
      "Enterprise plan purchased for brand kit features when Canva Teams would suffice",
    ],
    optimizationTips: [
      "Keep occasional users on the free tier — it includes thousands of templates and basic design tools",
      "Audit which premium templates and stock images are actually being downloaded and used",
      "Use Canva as the standard for non-designers and reserve Adobe CC for professional design work only",
      "Share Canva Teams folders to maximize collaboration without needing individual Pro accounts",
    ],
    alternatives: ["Adobe Express", "Visme", "Piktochart"],
    idealFor: "Marketing teams and non-designers of 5-500 creating visual content",
    marketPosition: "The dominant template-driven design tool for non-designers; complementary to Adobe Creative Cloud rather than a direct replacement.",
    commonPriceRange: "$13-30 per user per month for Pro and Teams tiers, with a generous free tier for individuals.",
    signatureWastePattern: "Pro or Teams seats paid for marketing colleagues who use Canva less than once a month and could comfortably stay on the free tier.",
  },
  {
    slug: "mailchimp",
    name: "Mailchimp",
    category: "Marketing",
    description:
      "Mailchimp is an email marketing and automation platform offering campaign management, audience segmentation, landing pages, and analytics for growing businesses.",
    website: "https://mailchimp.com",
    pricingModel: "Tiered (based on contacts and features)",
    startingPrice: "Free (up to 500 contacts); $13/month (Essentials)",
    averageCostPerUser: 30,
    typicalCompanySpend: "$50-$5,000/month",
    commonWastePatterns: [
      "Premium or Standard plan features (advanced segmentation, multivariate testing) that go unused",
      "Paying for a large contact list that includes many unengaged or bounced email addresses",
      "Using Mailchimp for transactional email when Mandrill or SendGrid would be more cost-effective",
      "Overlapping with HubSpot Marketing Hub or another marketing automation platform",
    ],
    optimizationTips: [
      "Clean your contact list quarterly — remove unsubscribed, bounced, and unengaged contacts to lower your tier cost",
      "Use the Essentials plan unless you specifically need the automation journeys in Standard or multivariate testing in Premium",
      "Consolidate email marketing into either Mailchimp or your CRM's built-in email tools — not both",
      "Use Mailchimp's free tier for small lists and simple campaigns before upgrading",
    ],
    alternatives: ["ConvertKit", "Brevo (Sendinblue)", "ActiveCampaign"],
    idealFor: "Small businesses and marketing teams managing 500-100,000 contacts",
    marketPosition: "Long-running SMB email-marketing platform owned by Intuit; competes with ConvertKit, Brevo, and ActiveCampaign for growth-stage senders.",
    commonPriceRange: "$13-350 per month based on contact tier and feature set across Essentials, Standard, and Premium plans.",
    signatureWastePattern: "Contact tier inflated by unsubscribed and bounced addresses that should have been pruned at the last quarterly hygiene cycle.",
  },
  {
    slug: "sendgrid",
    name: "SendGrid",
    category: "Marketing",
    description:
      "SendGrid (by Twilio) is a cloud-based email delivery service providing APIs for transactional and marketing email, delivery optimization, and analytics.",
    website: "https://sendgrid.com",
    pricingModel: "Tiered (based on monthly email volume)",
    startingPrice: "Free (100 emails/day); $19.95/month (Essentials, 50K emails)",
    averageCostPerUser: 20,
    typicalCompanySpend: "$20-$5,000/month",
    commonWastePatterns: [
      "Paying for an email tier well above actual monthly send volume",
      "Pro plan features (dedicated IP, sub-user management) purchased but not utilized",
      "Using SendGrid for marketing campaigns when Mailchimp or HubSpot provides better tools for that use case",
      "Dedicated IPs maintained for low-volume senders where shared IPs would suffice",
    ],
    optimizationTips: [
      "Right-size your plan based on actual monthly email volume rather than projected peaks",
      "Use shared IP pools unless your volume exceeds 100K emails/month and you need IP reputation control",
      "Separate transactional (SendGrid) and marketing (Mailchimp/HubSpot) email to optimize costs for each",
      "Monitor email bounce rates and clean suppression lists to avoid paying to send to invalid addresses",
    ],
    alternatives: ["Amazon SES", "Postmark", "Mailgun"],
    idealFor: "Developers and companies sending 10K-10M transactional or marketing emails monthly",
    marketPosition: "Leading developer-first transactional email API, owned by Twilio; competes with Postmark, Mailgun, and Amazon SES.",
    commonPriceRange: "$19.95-89.95 per month for Essentials and Pro plans, scaled by monthly send volume.",
    signatureWastePattern: "Email-volume tier paid for at projected peak while actual monthly sends sit at a fraction of the included allotment.",
  },
  {
    slug: "aws",
    name: "AWS",
    category: "Cloud Infrastructure",
    description:
      "Amazon Web Services is the world's leading cloud platform, providing compute, storage, database, networking, AI/ML, and 200+ other services for businesses of all sizes.",
    website: "https://aws.amazon.com",
    pricingModel: "Usage-based (pay-as-you-go per service)",
    startingPrice: "Free Tier available; pay-as-you-go pricing",
    averageCostPerUser: 200,
    typicalCompanySpend: "$1,000-$500,000/month",
    commonWastePatterns: [
      "EC2 instances running 24/7 when they are only needed during business hours or for periodic workloads",
      "Oversized instances — many workloads run on instance types far larger than CPU and memory usage require",
      "Unattached EBS volumes, unused Elastic IPs, and idle load balancers accumulating charges",
      "Not utilizing Reserved Instances or Savings Plans despite having predictable baseline workloads",
    ],
    optimizationTips: [
      "Right-size EC2 instances using AWS Cost Explorer recommendations — most companies can downsize 30-40% of instances",
      "Purchase Reserved Instances or Savings Plans for predictable workloads to save 30-72% over On-Demand pricing",
      "Schedule non-production instances (dev, staging, QA) to stop during nights and weekends",
      "Clean up unused resources: detached EBS volumes, old snapshots, unused Elastic IPs, and idle NAT Gateways",
    ],
    alternatives: ["Google Cloud Platform", "Microsoft Azure", "DigitalOcean"],
    idealFor: "Organizations of all sizes running cloud workloads, from startups to enterprises",
    marketPosition: "Market-leading cloud infrastructure provider; the default for most engineering organizations across startup and enterprise tiers.",
    commonPriceRange: "Usage-based; spend varies dramatically by service, region, instance family, and reservation strategy.",
    signatureWastePattern: "Idle EC2 and RDS instances and unattached EBS volumes left running long after the development sprint that spun them up concluded.",
  },
  {
    slug: "azure",
    name: "Microsoft Azure",
    category: "Cloud Infrastructure",
    description:
      "Microsoft Azure is a comprehensive cloud computing platform offering compute, data, AI, IoT, and hybrid cloud services with deep integration into the Microsoft ecosystem.",
    website: "https://azure.microsoft.com",
    pricingModel: "Usage-based (pay-as-you-go per service)",
    startingPrice: "Free Tier available; pay-as-you-go pricing",
    averageCostPerUser: 180,
    typicalCompanySpend: "$1,000-$400,000/month",
    commonWastePatterns: [
      "Virtual machines running 24/7 for development and testing workloads that are only used during business hours",
      "Oversized VM SKUs where workloads consistently use less than 20% of allocated CPU and memory",
      "Orphaned disks, public IPs, and unused App Service plans left behind after resource deletion",
      "Not leveraging Azure Hybrid Benefit for Windows Server and SQL Server licenses",
    ],
    optimizationTips: [
      "Use Azure Advisor cost recommendations to identify and right-size underutilized VMs",
      "Purchase Azure Reserved Instances for 1 or 3 years on stable workloads to save up to 72%",
      "Apply Azure Hybrid Benefit to bring existing Windows Server and SQL licenses to Azure for significant discounts",
      "Set up auto-shutdown schedules for non-production VMs to eliminate after-hours costs",
    ],
    alternatives: ["AWS", "Google Cloud Platform", "DigitalOcean"],
    idealFor: "Enterprises with existing Microsoft investments and hybrid cloud strategies",
    marketPosition: "Number-two hyperscaler globally; the default cloud for enterprises already standardized on Microsoft 365 and Active Directory.",
    commonPriceRange: "Usage-based; pricing varies by service, region, and reservation, with significant Hybrid Benefit discounts on Windows workloads.",
    signatureWastePattern: "Windows Server and SQL Server VMs billed at full retail because Azure Hybrid Benefit was never applied to existing on-prem licenses.",
  },
  {
    slug: "google-cloud",
    name: "Google Cloud Platform",
    category: "Cloud Infrastructure",
    description:
      "Google Cloud Platform provides cloud computing, data analytics, machine learning, and enterprise solutions powered by Google's infrastructure.",
    website: "https://cloud.google.com",
    pricingModel: "Usage-based (pay-as-you-go per service)",
    startingPrice: "Free Tier available; pay-as-you-go pricing",
    averageCostPerUser: 170,
    typicalCompanySpend: "$1,000-$300,000/month",
    commonWastePatterns: [
      "Compute Engine instances running idle or oversized for their actual workload requirements",
      "BigQuery costs from scanning full tables instead of using partitioned and clustered tables",
      "Cloud Storage buckets retaining data in expensive storage classes when archival tiers would suffice",
      "Not applying Committed Use Discounts despite predictable compute consumption",
    ],
    optimizationTips: [
      "Apply Committed Use Discounts (CUDs) for predictable Compute Engine and Cloud SQL workloads for 1-3 year savings",
      "Use Preemptible or Spot VMs for batch processing, CI/CD, and fault-tolerant workloads to save up to 80%",
      "Optimize BigQuery costs by using partitioned tables, clustering, and controlling slot usage",
      "Set lifecycle rules on Cloud Storage buckets to automatically move aged data to Nearline or Coldline tiers",
    ],
    alternatives: ["AWS", "Microsoft Azure", "DigitalOcean"],
    idealFor: "Data-driven organizations and teams heavily using analytics and machine learning",
    marketPosition: "Number-three hyperscaler; the cloud of choice for data-heavy and ML-first organizations thanks to BigQuery and Vertex AI.",
    commonPriceRange: "Usage-based; pricing varies by service, region, and Committed Use Discount commitments.",
    signatureWastePattern: "BigQuery query costs running on full-table scans because partitioning and clustering were never configured on the largest tables.",
  },
  {
    slug: "heroku",
    name: "Heroku",
    category: "Cloud Infrastructure",
    description:
      "Heroku is a platform-as-a-service (PaaS) enabling developers to deploy, manage, and scale web applications without managing infrastructure directly.",
    website: "https://heroku.com",
    pricingModel: "Per dyno/month + add-on usage",
    startingPrice: "$5/month (Eco dynos); $25/month (Basic)",
    averageCostPerUser: 50,
    typicalCompanySpend: "$100-$5,000/month",
    commonWastePatterns: [
      "Performance-L dynos ($500/month each) for applications that would run fine on Standard-2X",
      "Heroku Postgres Premium plans maintained for databases that rarely approach plan limits",
      "Multiple staging and review apps running continuously when they could be spun up on-demand",
      "Add-ons like logging, monitoring, and SSL that could be replaced with free alternatives",
    ],
    optimizationTips: [
      "Right-size dynos based on actual memory and CPU usage rather than anticipated peak load",
      "Use review apps that auto-deploy from PRs and auto-destroy when merged instead of persistent staging",
      "Evaluate whether migrating to Railway, Render, or direct cloud services (AWS/GCP) would reduce costs",
      "Replace paid add-ons with free-tier alternatives or built-in cloud provider services",
    ],
    alternatives: ["Railway", "Render", "Fly.io"],
    idealFor: "Small development teams of 2-30 wanting managed deployment simplicity",
    marketPosition: "Original PaaS for web apps, now part of Salesforce; squeezed by Render, Railway, and Fly.io on the low end and direct cloud on the high end.",
    commonPriceRange: "$5-500 per dyno per month across Eco, Basic, Standard, and Performance tiers, plus add-on usage.",
    signatureWastePattern: "Performance-L dynos at $500 each kept on for apps whose memory and CPU profile would run comfortably on Standard-2X.",
  },
  {
    slug: "vercel",
    name: "Vercel",
    category: "Cloud Infrastructure",
    description:
      "Vercel is a cloud platform for frontend frameworks and static sites, providing instant deployments, serverless functions, and edge computing with a focus on Next.js.",
    website: "https://vercel.com",
    pricingModel: "Per member/month + usage-based",
    startingPrice: "Free (Hobby); $20/member/month (Pro)",
    averageCostPerUser: 20,
    typicalCompanySpend: "$100-$5,000/month",
    commonWastePatterns: [
      "Pro team seats for developers who only preview deployments and never manage configurations",
      "Serverless function execution and bandwidth overages from unoptimized builds",
      "Enterprise plan ($500+/month) features like custom SLAs and advanced security that are not needed",
      "Running multiple team workspaces when projects could be consolidated",
    ],
    optimizationTips: [
      "Keep non-essential team members on individual Hobby accounts for preview access only",
      "Optimize serverless function cold starts and build times to stay within Pro plan limits",
      "Monitor bandwidth and function invocation usage proactively to avoid surprise overage charges",
      "Evaluate whether Netlify or Cloudflare Pages could serve simpler static sites at lower cost",
    ],
    alternatives: ["Netlify", "Cloudflare Pages", "AWS Amplify"],
    idealFor: "Frontend teams of 3-50 deploying Next.js and Jamstack applications",
    marketPosition: "Premier Next.js hosting platform; the default deployment target for React and Jamstack teams, with Netlify and Cloudflare Pages as competitors.",
    commonPriceRange: "$20-50 per member per month for Pro plus usage-based bandwidth and serverless function execution.",
    signatureWastePattern: "Bandwidth and serverless function overages caused by unoptimized images and uncached API routes that quietly compound month over month.",
  },
  {
    slug: "netlify",
    name: "Netlify",
    category: "Cloud Infrastructure",
    description:
      "Netlify is a web development platform providing automated builds, deployments, serverless functions, and edge computing for modern web applications.",
    website: "https://netlify.com",
    pricingModel: "Per member/month + usage-based",
    startingPrice: "Free (Starter); $19/member/month (Pro)",
    averageCostPerUser: 19,
    typicalCompanySpend: "$100-$3,000/month",
    commonWastePatterns: [
      "Pro seats for team members who don't actively deploy or manage site configurations",
      "Build minute and bandwidth overages from frequent deployments or large sites",
      "Enterprise features purchased for teams that could operate within Pro plan limits",
      "Paying for Netlify Functions when builds are mostly static with minimal server-side needs",
    ],
    optimizationTips: [
      "Limit Pro seats to developers who actively deploy and use Netlify's CI/CD features",
      "Optimize build configurations with caching and incremental builds to reduce build minute usage",
      "Monitor bandwidth consumption and implement CDN caching strategies for high-traffic sites",
      "Compare with Vercel and Cloudflare Pages, which may offer better value for specific frameworks",
    ],
    alternatives: ["Vercel", "Cloudflare Pages", "AWS Amplify"],
    idealFor: "Frontend teams of 2-30 building Jamstack and static sites",
    marketPosition: "The Jamstack pioneer; primary alternative to Vercel for framework-agnostic frontend hosting and edge functions.",
    commonPriceRange: "$19-99 per member per month for Pro and Enterprise, plus usage charges for build minutes and bandwidth.",
    signatureWastePattern: "Build-minute overages from frequent CI deploys that never had build caching or incremental builds turned on.",
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    category: "Cloud Infrastructure",
    description:
      "Cloudflare provides CDN, DDoS protection, DNS, web application firewall, and edge computing services to secure and accelerate internet properties.",
    website: "https://cloudflare.com",
    pricingModel: "Per zone/month (tiered) + usage-based",
    startingPrice: "Free plan; $20/month (Pro per domain)",
    averageCostPerUser: 30,
    typicalCompanySpend: "$100-$10,000/month",
    commonWastePatterns: [
      "Business plan ($200/domain/month) for domains that only need Pro-level features",
      "Paying for Cloudflare Workers and R2 storage that are underutilized or over-provisioned",
      "Multiple domain plans when a Cloudflare for Enterprise agreement would provide better value",
      "Argo Smart Routing or load balancing add-ons enabled for low-traffic sites",
    ],
    optimizationTips: [
      "Match each domain to the right plan tier — most sites work perfectly on the Free or Pro plan",
      "Consolidate domain management and negotiate enterprise pricing for 10+ domains",
      "Monitor Workers and R2 usage to ensure you are within free-tier limits before paying",
      "Disable premium add-ons (Argo, Load Balancing) for sites that don't need latency optimization",
    ],
    alternatives: ["AWS CloudFront", "Fastly", "Akamai"],
    idealFor: "Websites and web applications of any scale needing CDN and security",
    marketPosition: "The dominant standalone CDN and DDoS-mitigation provider; competes with AWS CloudFront, Fastly, and Akamai for edge security and performance.",
    commonPriceRange: "$20-200 per domain per month for Pro and Business plans, plus usage-based fees for Workers, R2, and load balancing.",
    signatureWastePattern: "Business plans at $200 per domain locked in across many sites that would be perfectly served on the Free or Pro plan.",
  },
  {
    slug: "okta",
    name: "Okta",
    category: "Security",
    description:
      "Okta is an identity and access management platform providing SSO, multi-factor authentication, lifecycle management, and API security for enterprises.",
    website: "https://okta.com",
    pricingModel: "Per user/month (modular pricing by product)",
    startingPrice: "$2/user/month (SSO); $3/user/month (MFA)",
    averageCostPerUser: 8,
    typicalCompanySpend: "$500-$20,000/month",
    commonWastePatterns: [
      "Universal Directory and Lifecycle Management licenses for organizations that manage users in Azure AD",
      "Okta licenses for contractors and external users who could use cheaper or free identity federation",
      "Advanced Server Access or API Access Management products purchased but never fully deployed",
      "Paying for Okta alongside Microsoft Entra ID (Azure AD), creating redundant identity providers",
    ],
    optimizationTips: [
      "Evaluate whether Microsoft Entra ID (included with Microsoft 365) can replace Okta for SSO and MFA",
      "Use Okta's outsourced user management for contractors instead of full internal licenses",
      "Remove add-on modules (Advanced Server Access, Workflows) that are not actively used",
      "Negotiate volume discounts for organizations with 500+ users",
    ],
    alternatives: ["Microsoft Entra ID", "Auth0", "OneLogin"],
    idealFor: "Enterprises with 100-10,000+ employees needing centralized identity management",
    marketPosition: "Independent enterprise identity leader; primary competitor is Microsoft Entra ID, which is bundled with Microsoft 365 Business and E-tier plans.",
    commonPriceRange: "$2-15 per user per month per product, with bundled Workforce Identity packages at the higher end.",
    signatureWastePattern: "Okta SSO and Lifecycle Management billed across the workforce while Microsoft Entra ID is already paid for inside an existing M365 subscription.",
  },
  {
    slug: "auth0",
    name: "Auth0",
    category: "Security",
    description:
      "Auth0 (by Okta) is a customer identity platform providing authentication, authorization, and user management APIs for application developers.",
    website: "https://auth0.com",
    pricingModel: "Tiered (based on monthly active users)",
    startingPrice: "Free (up to 7,500 MAU); $35/month (Essentials, 500 MAU)",
    averageCostPerUser: 0.05,
    typicalCompanySpend: "$100-$10,000/month",
    commonWastePatterns: [
      "Professional or Enterprise tiers for applications that could work within Essentials feature set",
      "Paying per MAU for users who authenticate infrequently and inflate active user counts",
      "Running Auth0 for internal workforce identity when Okta or Azure AD is already in use",
      "Custom domain and branding add-ons enabled across all environments including development",
    ],
    optimizationTips: [
      "Use the free tier for development and staging environments to avoid unnecessary MAU charges",
      "Implement token caching and session management to reduce the frequency of authentication calls",
      "Separate customer identity (Auth0) from workforce identity (Okta/Azure AD) to avoid overlap",
      "Monitor MAU trends and negotiate custom pricing before hitting tier thresholds",
    ],
    alternatives: ["Firebase Auth", "Clerk", "Supabase Auth"],
    idealFor: "SaaS developers building customer-facing applications with 1K-1M+ users",
    marketPosition: "Leading customer-identity (CIAM) developer platform owned by Okta; primary alternatives are Clerk, Firebase Auth, and Supabase Auth.",
    commonPriceRange: "$35-1,500+ per month based on monthly active users across Essentials, Professional, and Enterprise tiers.",
    signatureWastePattern: "Per-MAU charges inflated by development and staging environments running on the same paid tenant as production.",
  },
  {
    slug: "1password",
    name: "1Password",
    category: "Security",
    description:
      "1Password is a password manager for teams and businesses, providing secure credential storage, sharing, secret management, and SSO integration.",
    website: "https://1password.com",
    pricingModel: "Per user/month",
    startingPrice: "$7.99/user/month (Teams Starter Pack)",
    averageCostPerUser: 7.99,
    typicalCompanySpend: "$100-$3,000/month",
    commonWastePatterns: [
      "Business plan ($14/user/month) for teams that don't use advanced reporting, custom groups, or VPN features",
      "Licenses for employees who never activated their account or stopped using the vault",
      "Overlapping with browser-built-in password managers or another tool like LastPass or Bitwarden",
      "Enterprise plan features like SCIM provisioning and custom security policies unused by smaller teams",
    ],
    optimizationTips: [
      "Start with the Teams Starter Pack and only upgrade to Business when advanced admin controls are needed",
      "Audit account activity and remove licenses for users who never activated or haven't logged in for 60+ days",
      "Standardize on one password manager across the organization to eliminate redundancy",
      "Leverage 1Password's integration with Okta or Azure AD for automated provisioning and deprovisioning",
    ],
    alternatives: ["Bitwarden", "LastPass", "Dashlane"],
    idealFor: "Teams of 10-500 needing secure credential management",
    marketPosition: "The premium business password manager; widely regarded as the most polished option for tech-savvy teams over LastPass and Dashlane.",
    commonPriceRange: "$7.99-19.95 per user per month for Teams Starter, Business, and Enterprise tiers.",
    signatureWastePattern: "Vault licenses billed for employees who never activated their account or stopped opening 1Password months ago.",
  },
  {
    slug: "lastpass",
    name: "LastPass",
    category: "Security",
    description:
      "LastPass is a password management solution offering secure password vaults, auto-fill, password sharing, and dark web monitoring for businesses.",
    website: "https://lastpass.com",
    pricingModel: "Per user/month",
    startingPrice: "$4/user/month (Teams); $7/user/month (Business)",
    averageCostPerUser: 7,
    typicalCompanySpend: "$100-$2,500/month",
    commonWastePatterns: [
      "Business plan licenses for teams that only need shared vaults and basic reporting (Teams would suffice)",
      "Inactive accounts for departed employees still consuming licenses",
      "Running LastPass alongside 1Password or Bitwarden due to incomplete migration",
      "Advanced SSO and MFA add-ons purchased but connected to only a few applications",
    ],
    optimizationTips: [
      "Evaluate switching to Bitwarden (from $4/user/month) for comparable features at a lower price",
      "Automate user deprovisioning through directory integration to reclaim licenses immediately on offboarding",
      "Use the Teams plan if you don't need SSO, advanced policies, or directory sync",
      "Consolidate to a single password manager and complete any pending migration from competing tools",
    ],
    alternatives: ["1Password", "Bitwarden", "Dashlane"],
    idealFor: "Teams of 5-500 needing affordable password management",
    marketPosition: "Long-running enterprise password manager that has lost share to 1Password and Bitwarden following well-publicized security incidents.",
    commonPriceRange: "$4-9 per user per month across Teams and Business plans.",
    signatureWastePattern: "LastPass seats billed alongside 1Password or Bitwarden because a planned migration was abandoned partway through and never closed out.",
  },
  {
    slug: "docusign",
    name: "DocuSign",
    category: "Productivity",
    description:
      "DocuSign is an electronic signature and contract lifecycle management platform enabling businesses to send, sign, and manage agreements digitally.",
    website: "https://docusign.com",
    pricingModel: "Per user/month (tiered, envelope-based)",
    startingPrice: "$10/month (Personal); $25/user/month (Standard)",
    averageCostPerUser: 40,
    typicalCompanySpend: "$200-$5,000/month",
    commonWastePatterns: [
      "Business Pro or Enterprise licenses for users who only need basic signature collection",
      "Envelope overage charges from plans that don't match actual monthly signing volume",
      "Multiple DocuSign accounts across departments instead of a consolidated enterprise agreement",
      "CLM (Contract Lifecycle Management) add-on purchased but used only for basic e-signature",
    ],
    optimizationTips: [
      "Match plan tiers to actual envelope usage — most individuals only need the Standard plan",
      "Consolidate all DocuSign accounts into a single enterprise agreement for volume discounts",
      "Evaluate PandaDoc or HelloSign as lower-cost alternatives for basic e-signature needs",
      "Use DocuSign's built-in templates and PowerForms to reduce the number of envelopes consumed per workflow",
    ],
    alternatives: ["PandaDoc", "HelloSign (Dropbox Sign)", "Adobe Acrobat Sign"],
    idealFor: "Companies with 10-500 employees processing regular document signing workflows",
    marketPosition: "Dominant e-signature platform with the largest enterprise install base; competes with PandaDoc, Dropbox Sign, and Adobe Acrobat Sign.",
    commonPriceRange: "$10-65 per user per month across Personal, Standard, and Business Pro tiers, plus envelope pricing on enterprise plans.",
    signatureWastePattern: "Envelope-overage charges paid each month because the plan tier was sized to last year's signing volume rather than this quarter's.",
  },
  {
    slug: "pandadoc",
    name: "PandaDoc",
    category: "Productivity",
    description:
      "PandaDoc is a document automation platform for creating, approving, and e-signing proposals, quotes, contracts, and other business documents.",
    website: "https://pandadoc.com",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "Free (e-signatures only); $35/user/month (Essentials)",
    averageCostPerUser: 49,
    typicalCompanySpend: "$200-$3,000/month",
    commonWastePatterns: [
      "Business plan seats for users who only send occasional documents and could use the free e-sign tier",
      "Overlapping with DocuSign or HelloSign for e-signature functionality",
      "Paying for the CRM integration add-on when manual document creation suffices",
      "Enterprise features like custom branding, roles, and content locking unused by small teams",
    ],
    optimizationTips: [
      "Use PandaDoc's free tier for users who only need electronic signature capability",
      "Assign paid seats only to sales reps or team members who create documents regularly",
      "Consolidate e-signature tools — choose either PandaDoc or DocuSign, not both",
      "Leverage PandaDoc's CRM integrations to automate document creation and reduce manual work",
    ],
    alternatives: ["DocuSign", "Proposify", "Better Proposals"],
    idealFor: "Sales teams of 5-100 creating proposals, quotes, and contracts",
    marketPosition: "Leading sales-document automation platform; primary alternative to DocuSign for teams that build proposals as well as send them out for signature.",
    commonPriceRange: "$19-49 per user per month for Essentials and Business tiers, plus enterprise quotes for larger teams.",
    signatureWastePattern: "Business-tier seats handed to internal users who only need basic e-signature and could sit on the free e-sign plan instead.",
  },
  {
    slug: "calendly",
    name: "Calendly",
    category: "Productivity",
    description:
      "Calendly is a scheduling automation platform that eliminates back-and-forth emails for meeting scheduling with booking pages, team scheduling, and calendar integrations.",
    website: "https://calendly.com",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "Free (1 event type); $10/user/month (Standard)",
    averageCostPerUser: 12,
    typicalCompanySpend: "$50-$1,500/month",
    commonWastePatterns: [
      "Teams plan seats for employees who schedule fewer than 5 meetings per month externally",
      "Paying for Calendly when Google Calendar or Outlook's built-in scheduling features would suffice",
      "Standard or Teams plans for users who only need one event type (covered by the free tier)",
      "Routing and round-robin features purchased for teams that don't handle inbound scheduling",
    ],
    optimizationTips: [
      "Use the free tier for users who only need a single booking link for one meeting type",
      "Evaluate whether built-in scheduling features in Google Calendar or Microsoft Bookings cover your needs",
      "Assign Teams plan seats only to sales and customer-facing roles that schedule frequently",
      "Consolidate scheduling tools if multiple teams use different solutions (Calendly, Doodle, Cal.com)",
    ],
    alternatives: ["Cal.com", "SavvyCal", "Microsoft Bookings"],
    idealFor: "Sales and customer-facing teams of 5-200 scheduling external meetings",
    marketPosition: "Market-leading scheduling-link tool; primary alternatives are Cal.com, SavvyCal, and the Bookings tools bundled into Google and Microsoft suites.",
    commonPriceRange: "$10-20 per user per month for Standard and Teams tiers, with a free single-link plan available.",
    signatureWastePattern: "Teams-tier seats provisioned for employees who book fewer than five external meetings per month and do not need round-robin routing.",
  },
  {
    slug: "loom",
    name: "Loom",
    category: "Communication",
    description:
      "Loom is an async video messaging platform that lets teams record and share screen recordings, presentations, and video messages to communicate without meetings.",
    website: "https://loom.com",
    pricingModel: "Per creator/month (viewers free)",
    startingPrice: "Free (up to 25 videos); $15/creator/month (Business)",
    averageCostPerUser: 15,
    typicalCompanySpend: "$100-$2,000/month",
    commonWastePatterns: [
      "Business licenses for team members who record fewer than 2-3 videos per month",
      "Creator seats assigned to employees who only watch videos and could use free viewer access",
      "Enterprise plan features (SSO, advanced analytics) purchased for small teams",
      "Paying for Loom alongside other screen recording tools like CloudApp or Snagit",
    ],
    optimizationTips: [
      "Keep occasional recorders on the free plan (25 videos, 5 minutes per video) or as viewers",
      "Assign Business creator seats only to team members who regularly produce video content",
      "Consolidate screen recording tools — choose one platform for async video communication",
      "Use Loom's free viewer access for the majority of the team who only watch and comment",
    ],
    alternatives: ["Vidyard", "CloudApp", "Screencastify"],
    idealFor: "Remote teams of 10-500 using async video for communication and documentation",
    marketPosition: "Market leader in async video messaging, now part of Atlassian; primary alternatives are Vidyard and the recording tools built into Slack or Zoom.",
    commonPriceRange: "$15-22.50 per creator per month for Business and Enterprise tiers; viewers free.",
    signatureWastePattern: "Creator seats assigned to teammates who only ever watch videos and would do everything they need with free viewer access.",
  },
  {
    slug: "miro",
    name: "Miro",
    category: "Productivity",
    description:
      "Miro is a visual collaboration platform offering infinite whiteboards for brainstorming, diagramming, workshops, and agile ceremonies with real-time and async collaboration.",
    website: "https://miro.com",
    pricingModel: "Per member/month (tiered)",
    startingPrice: "Free (3 boards); $8/member/month (Starter)",
    averageCostPerUser: 16,
    typicalCompanySpend: "$100-$4,000/month",
    commonWastePatterns: [
      "Business plan seats for team members who participate in whiteboard sessions infrequently",
      "Paying for Miro alongside FigJam, which provides similar whiteboarding functionality",
      "Full member seats for stakeholders who only need to view and comment on boards",
      "Enterprise features like SSO and advanced security for teams under 50 people",
    ],
    optimizationTips: [
      "Use free guest access for participants who only need to view or occasionally contribute to boards",
      "Choose between Miro and FigJam — paying for both whiteboarding tools is redundant",
      "Keep the Starter plan for teams that don't need advanced diagramming or video chat features",
      "Limit paid seats to facilitators and regular content creators; keep everyone else as free viewers",
    ],
    alternatives: ["FigJam", "Lucidchart", "Whimsical"],
    idealFor: "Teams of 10-300 running workshops, brainstorming, and visual collaboration",
    marketPosition: "Dominant standalone collaborative whiteboard; competes mostly with FigJam, which is increasingly bundled inside existing Figma seats.",
    commonPriceRange: "$8-16 per member per month for Starter and Business tiers.",
    signatureWastePattern: "Full Miro member seats kept on for stakeholders who attend a board once a quarter and could participate as free guests.",
  },
  {
    slug: "clickup",
    name: "ClickUp",
    category: "Project Management",
    description:
      "ClickUp is an all-in-one productivity platform combining project management, docs, goals, whiteboards, and time tracking in a single tool for teams.",
    website: "https://clickup.com",
    pricingModel: "Per member/month (tiered)",
    startingPrice: "Free; $7/member/month (Unlimited)",
    averageCostPerUser: 12,
    typicalCompanySpend: "$100-$3,000/month",
    commonWastePatterns: [
      "Business plan seats for teams that only use task lists and don't leverage advanced automations or timelines",
      "Paying for ClickUp alongside other PM tools due to incomplete migration from Asana, Jira, or Monday.com",
      "Full member seats for stakeholders who only check project status occasionally",
      "ClickUp AI add-on purchased for the entire workspace when only a few members use it",
    ],
    optimizationTips: [
      "Use the free tier for small teams (up to 5 spaces) before committing to paid plans",
      "Complete the migration from other PM tools before paying for both ClickUp and the legacy tool",
      "Assign guest access to external collaborators and occasional viewers instead of full member seats",
      "Limit ClickUp AI seats to users who actively use the feature rather than enabling it workspace-wide",
    ],
    alternatives: ["Asana", "Monday.com", "Notion"],
    idealFor: "Teams of 5-500 wanting an affordable all-in-one project management solution",
    marketPosition: "Aggressive all-in-one project-management challenger to Asana and monday.com; positions on price and feature breadth.",
    commonPriceRange: "$7-19 per member per month for Unlimited, Business, and Business Plus tiers.",
    signatureWastePattern: "ClickUp seats running in parallel with Asana, Jira, or monday.com because the previous-tool migration was paused and never resumed.",
  },
  {
    slug: "basecamp",
    name: "Basecamp",
    category: "Project Management",
    description:
      "Basecamp is a project management and team communication tool offering to-do lists, message boards, file sharing, and group chat with a flat-fee pricing model.",
    website: "https://basecamp.com",
    pricingModel: "Flat fee (unlimited users)",
    startingPrice: "$15/user/month (standard); $349/month (Pro Unlimited, flat fee)",
    averageCostPerUser: 15,
    typicalCompanySpend: "$349-$500/month",
    commonWastePatterns: [
      "Paying the flat Pro Unlimited fee for teams smaller than 25 users where per-user pricing would be cheaper",
      "Using Basecamp for simple task management when free tools or existing PM software could cover the same needs",
      "Overlapping functionality with Slack for messaging, Asana for tasks, and Google Drive for file sharing",
      "Not utilizing Basecamp's built-in features and paying for separate tools that duplicate functionality",
    ],
    optimizationTips: [
      "Calculate whether per-user pricing ($15/user) or Pro Unlimited ($349/month) is more cost-effective for your team size",
      "Consolidate messaging (Slack) and task management (Asana/Trello) into Basecamp if it covers all needs",
      "Use Basecamp's built-in file storage, chat, and scheduling before paying for additional specialized tools",
      "Evaluate whether your team has outgrown Basecamp and would benefit from a more feature-rich PM platform",
    ],
    alternatives: ["Asana", "Monday.com", "Notion"],
    idealFor: "Teams of 10-100 wanting simple, straightforward project management",
    marketPosition: "Long-running flat-fee project-management tool from 37signals; deliberately simple compared to Asana, Jira, and monday.com.",
    commonPriceRange: "$15 per user per month or $349 per month flat for Pro Unlimited.",
    signatureWastePattern: "Pro Unlimited's $349 flat fee paid by a sub-25-person team where the per-user plan would land at less than half the cost.",
  },
  {
    slug: "freshdesk",
    name: "Freshdesk",
    category: "Customer Support",
    description:
      "Freshdesk by Freshworks is a customer support platform offering ticketing, self-service, automation, and multi-channel support for help desk teams.",
    website: "https://freshdesk.com",
    pricingModel: "Per agent/month (tiered)",
    startingPrice: "Free (up to 10 agents); $15/agent/month (Growth)",
    averageCostPerUser: 49,
    typicalCompanySpend: "$200-$8,000/month",
    commonWastePatterns: [
      "Pro or Enterprise licenses for agents who only handle basic email tickets (Growth would suffice)",
      "Paying for Freshdesk alongside Zendesk or Intercom from an incomplete migration",
      "Freshchat, Freshsales, and other Freshworks add-on products with low adoption",
      "Day pass agent seats being consumed by users who could use the free plan",
    ],
    optimizationTips: [
      "Use the free plan (up to 10 agents) for small support teams with basic email ticketing needs",
      "Match agent tiers to actual feature usage — most teams don't need Enterprise-level SLA and audit logs",
      "Complete migration from legacy support tools before paying for both Freshdesk and the old platform",
      "Implement self-service portals and knowledge bases to deflect tickets and reduce the agents needed",
    ],
    alternatives: ["Zendesk", "Help Scout", "Zoho Desk"],
    idealFor: "Support teams of 5-200 agents handling multi-channel customer support",
    marketPosition: "Mid-market customer-support platform from Freshworks; primary alternative to Zendesk for cost-sensitive teams that still want omnichannel.",
    commonPriceRange: "$15-79 per agent per month across Growth, Pro, and Enterprise tiers.",
    signatureWastePattern: "Pro or Enterprise agent licenses kept on after a Zendesk migration was abandoned, so both products are now billed in parallel.",
  },
  {
    slug: "pipedrive",
    name: "Pipedrive",
    category: "CRM",
    description:
      "Pipedrive is a sales-focused CRM designed for small and mid-size sales teams, offering visual pipeline management, activity tracking, and sales automation.",
    website: "https://pipedrive.com",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "$14/user/month (Essential)",
    averageCostPerUser: 49,
    typicalCompanySpend: "$200-$5,000/month",
    commonWastePatterns: [
      "Professional or Power plan seats for reps who only use basic pipeline and contact management",
      "Lead Booster, Web Visitors, and Campaigns add-ons with minimal usage",
      "Paying for Pipedrive alongside HubSpot CRM or Salesforce due to overlapping functionality",
      "Seats for former sales reps or team members who no longer actively sell",
    ],
    optimizationTips: [
      "Start with the Essential or Advanced plan and only upgrade when specific Professional features are needed",
      "Audit add-on usage quarterly — remove Lead Booster, Smart Docs, or Campaigns if adoption is low",
      "Consolidate CRM tools — run one CRM platform instead of paying for both Pipedrive and another CRM",
      "Remove seats for inactive users and recover licenses for new sales hires",
    ],
    alternatives: ["HubSpot CRM", "Salesforce", "Close"],
    idealFor: "Sales teams of 5-200 wanting a simple, pipeline-focused CRM",
    marketPosition: "Sales-focused CRM popular with SMB outbound teams; sits between simple tools like Close and full platforms like Salesforce or HubSpot.",
    commonPriceRange: "$14-99 per user per month across Essential, Advanced, Professional, and Power plans.",
    signatureWastePattern: "Lead Booster, Web Visitors, and Smart Docs add-ons billed monthly with adoption metrics that haven't moved since the trial ended.",
  },
  {
    slug: "airtable",
    name: "Airtable",
    category: "Productivity",
    description:
      "Airtable is a low-code platform combining spreadsheet simplicity with database power, offering custom apps, automations, and views for managing structured data.",
    website: "https://airtable.com",
    pricingModel: "Per user/month (tiered)",
    startingPrice: "Free (up to 1,000 records/base); $20/user/month (Team)",
    averageCostPerUser: 20,
    typicalCompanySpend: "$200-$5,000/month",
    commonWastePatterns: [
      "Business plan seats for users who only view data and don't create or configure automations",
      "Paying for Airtable alongside spreadsheets, project management tools, or dedicated databases",
      "Record and automation run overage charges from plans that don't match actual data volume",
      "Enterprise Scale features purchased for teams that operate within Business plan limits",
    ],
    optimizationTips: [
      "Use free read-only shared views for stakeholders who only need to see data, not edit it",
      "Evaluate whether your use case is better served by a dedicated PM tool (for projects) or database (for large datasets)",
      "Monitor record counts and automation runs to select the most cost-effective plan tier",
      "Consolidate scattered team databases into shared bases to reduce per-user seat waste",
    ],
    alternatives: ["Notion", "Smartsheet", "Google Sheets"],
    idealFor: "Teams of 5-200 managing structured data, workflows, and lightweight applications",
    marketPosition: "Leading low-code spreadsheet-database hybrid; competes with Notion databases on the lightweight end and Smartsheet upmarket.",
    commonPriceRange: "$20-45 per seat per month for Team and Business tiers, with record and automation overage fees beyond that.",
    signatureWastePattern: "Record-count and automation-run overages racked up because a couple of bases grew unchecked past the plan tier limits.",
  },
  {
    slug: "webflow",
    name: "Webflow",
    category: "Design",
    description:
      "Webflow is a visual web development platform enabling designers to build responsive websites, CMS-driven content, and e-commerce stores without writing code.",
    website: "https://webflow.com",
    pricingModel: "Per site/month + workspace seats",
    startingPrice: "Free (staging); $14/month (Basic site plan)",
    averageCostPerUser: 30,
    typicalCompanySpend: "$100-$3,000/month",
    commonWastePatterns: [
      "CMS or Business site plans for sites that are essentially static marketing pages (Basic would work)",
      "Multiple workspace seats for team members who rarely log in to edit the site",
      "E-commerce plan features activated on sites that don't sell products online",
      "Hosting multiple low-traffic sites on individual plans instead of consolidating under a workspace",
    ],
    optimizationTips: [
      "Match site plans to actual needs — most marketing sites only need Basic ($14/month), not CMS ($23/month)",
      "Reduce workspace editor seats and use Webflow's Editor role for content-only contributors",
      "Consolidate sites under a workspace plan if you manage multiple Webflow sites",
      "Evaluate whether a simpler static site generator (Next.js + Vercel) would be more cost-effective long-term",
    ],
    alternatives: ["WordPress", "Framer", "Squarespace"],
    idealFor: "Design teams and agencies of 2-50 building marketing websites without code",
    marketPosition: "Visual-first website builder favored by design-led teams; primary alternatives are WordPress and the newer challenger Framer.",
    commonPriceRange: "$14-49 per site per month across Basic, CMS, and Business site plans, plus workspace seat fees.",
    signatureWastePattern: "CMS or Business site plans paid for static marketing pages whose feature usage matches what the cheaper Basic site plan covers.",
  },
  {
    slug: "semrush",
    name: "Semrush",
    category: "Marketing",
    description:
      "Semrush is an all-in-one digital marketing platform providing SEO, PPC, content marketing, social media, and competitive research tools for marketers.",
    website: "https://semrush.com",
    pricingModel: "Per plan/month (tiered with user add-ons)",
    startingPrice: "$139.95/month (Pro, 1 user)",
    averageCostPerUser: 139.95,
    typicalCompanySpend: "$140-$5,000/month",
    commonWastePatterns: [
      "Guru or Business plans purchased for features like historical data or API access that are rarely used",
      "Additional user seats ($45-100/user/month) for team members who use the tool infrequently",
      "Paying for Semrush alongside Ahrefs, Moz, or SimilarWeb for overlapping SEO and analytics data",
      "Content Marketing Platform, Social Media, and Local add-ons with low utilization",
    ],
    optimizationTips: [
      "Audit which Semrush features your team actually uses — Pro covers most standard SEO and PPC research needs",
      "Share a single Pro account across a small team if only 1-2 people use it regularly (within TOS limits)",
      "Choose one SEO platform (Semrush OR Ahrefs) and cancel the other to eliminate redundant subscriptions",
      "Remove add-on products with low adoption and use free alternatives for social media scheduling or local SEO",
    ],
    alternatives: ["Ahrefs", "Moz Pro", "SE Ranking"],
    idealFor: "Marketing teams of 1-50 managing SEO, content, and competitive analysis",
    marketPosition: "Leading all-in-one digital marketing platform; primary alternative to Ahrefs for SEO research and competitive analysis at scale.",
    commonPriceRange: "$139.95-499.95 per month for Pro, Guru, and Business plans, plus per-user add-on fees for additional seats.",
    signatureWastePattern: "Two SEO platforms billed in parallel because Semrush and Ahrefs (or Moz) overlap and the redundancy was never resolved.",
  },
]

export function getToolBySlug(slug: string): SaasToolData | undefined {
  return saasTools.find((tool) => tool.slug === slug)
}

export function getToolsByCategory(category: string): SaasToolData[] {
  return saasTools.filter((tool) => tool.category === category)
}

export function getRelatedTools(tool: SaasToolData, limit = 4): SaasToolData[] {
  return saasTools
    .filter((t) => t.category === tool.category && t.slug !== tool.slug)
    .slice(0, limit)
}

export function getAllCategories(): string[] {
  return [...new Set(saasTools.map((tool) => tool.category))]
}
